id: P005476
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:52:35.427256
source_metadata:
  id: bdr:W1KG16567
  title: དགའ་ལྡན་ཁྱུང་ཆེན་རྫོང་།
  author: ''
  volumes:
    758c14657aa84353bb89361cd326fabc:
      image_group_id: I2PD17883
      title: ''
      volume_number: 1
      total_pages: 260
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
